"""Recreating migrations

Revision ID: 193d6014810f
Revises: 
Create Date: 2025-03-11 08:29:29.420203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193d6014810f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(None, ['phonenumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phonenumber')

    # ### end Alembic commands ###
