"""Added a new field to User model

Revision ID: 8dbab5c2fda4
Revises: 0eacf651ced1
Create Date: 2025-03-18 15:01:13.177696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbab5c2fda4'
down_revision = '0eacf651ced1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sales_count')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sales_count', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
