"""Added a new field to User model

Revision ID: 998a62319bfc
Revises: 8dbab5c2fda4
Create Date: 2025-03-18 15:09:59.931029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998a62319bfc'
down_revision = '8dbab5c2fda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sales_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sales_count')
        batch_op.drop_column('image_url')

    op.create_table('product_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_image_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_image_pkey')
    )
    # ### end Alembic commands ###
